server:
  port: 7005

spring:
  devtools:
    restart:
      #需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**

crypto:
  path: /root/moonbox/data/
  # path: D:\\moonbox\\data\\

secret:
  path: /root/moonbox/secret.properties
  # path: D:\\moonbox\\secret.properties

